image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: dotnet fake build --target run

vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.9:BMArOoGwWqKRrH6s4E2/AQ==
    - ionide.ionide-fsharp@5.1.0:p/YohvQ0Y0nyskT2GD2b3g==