image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: dotnet fake build --target run

vscode:
  extensions:
    - ms-dotnettools.csharp@1.23.8:iO8KaJulQm9UBFXlmZNiog==
    - muhammad-sammy.csharp@1.23.9:BMArOoGwWqKRrH6s4E2/AQ==
    - ionide.ionide-fsharp@5.3.2:ktwOdXq2H8VHS6SX8scVIw==