image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: dotnet fake build --target run

vscode:
  extensions:
    - ionide.ionide-fsharp@5.1.0:p/YohvQ0Y0nyskT2GD2b3g==
    - muhammad-sammy.csharp@1.23.8:sQVKBcQ6FdF5kPQ+V6fc5Q==
    - ms-dotnettools.csharp@1.23.8:iO8KaJulQm9UBFXlmZNiog==